'use client';

import { useState } from 'react';
import { AnalysisResult, Bug, Severity, FixResponse } from '@/app/libs/types';
import CodeEditor from '@/app/components/CodeEditor';
import styles from '@/app/styles/BugReport.module.css';

interface BugReportProps {
  result: AnalysisResult;
  originalCode?: string;
}

function BugItem({ bug }: { bug: Bug }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className={`${styles.bugItem} ${styles[bug.severity]}`}>
      <div className={styles.bugHeader} onClick={() => setExpanded(!expanded)}>
        <span className={styles.bugSeverity}>{bug.severity}</span>
        <span className={styles.bugLine}>L{bug.line}</span>
        <span className={styles.bugTitle}>{bug.title}</span>
        <span className={`${styles.expandIcon} ${expanded ? styles.expanded : ''}`}>▼</span>
      </div>

      {expanded && (
        <div className={styles.bugBody}>
          <p className={styles.bugDescription}>{bug.description}</p>

          {bug.codeSnippet && (
            <div className={styles.bugCodeSnippet}>{bug.codeSnippet}</div>
          )}

          <div className={styles.bugFix}>
            <div className={styles.bugFixTitle}>
              <span>✓</span>
              <span>How to Fix</span>
            </div>
            <p className={styles.bugFixText}>{bug.fix.explanation}</p>
            {bug.fix.code && (
              <div className={styles.fixCode}>{bug.fix.code}</div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function exportAsJSON(result: AnalysisResult): void {
  const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `bugradar-report-${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportAsMarkdown(result: AnalysisResult): void {
  const severityEmoji: Record<Severity, string> = { critical: '🔴', warning: '🟡', info: '🔵' };
  const lines = [
    `# BugRadar Analysis Report`,
    ``,
    `**Language:** ${result.language}  `,
    `**Mode:** ${result.analysisMode ?? 'static'}  `,
    `**Code Score:** ${result.score}/100  `,
    `**Total Issues:** ${result.totalBugs} (${result.criticalCount} critical, ${result.warningCount} warnings, ${result.infoCount} info)`,
    ``,
    `## Summary`,
    ``,
    result.summary,
    ``,
  ];

  if (result.aiInsights) {
    lines.push(`## AI Insights`, ``);
    lines.push(result.aiInsights.overallAssessment, ``);
    if (result.aiInsights.topPriorities?.length) {
      lines.push(`**Top Priorities:**`);
      result.aiInsights.topPriorities.forEach((p) => lines.push(`- ${p}`));
      lines.push(``);
    }
  }

  lines.push(`## Issues Found`, ``);
  result.bugs.forEach((bug, i) => {
    lines.push(
      `### ${i + 1}. ${severityEmoji[bug.severity]} ${bug.title}`,
      ``,
      `**Severity:** \`${bug.severity}\`  `,
      `**Line:** ${bug.line}  `,
      `**Type:** \`${bug.type}\``,
      ``,
      bug.description,
      ``,
    );
    if (bug.codeSnippet) {
      lines.push('**Problematic Code:**', '```', bug.codeSnippet, '```', ``);
    }
    lines.push(`**Fix:** ${bug.fix.explanation}`);
    if (bug.fix.code) lines.push('```', bug.fix.code, '```');
    lines.push(``);
  });

  lines.push(`---`, `*Generated by BugRadar · ${new Date().toISOString()}*`);

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `bugradar-report-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

interface FixModalProps {
  originalCode: string;
  language: string;
  bugs: Bug[];
  onClose: () => void;
}

function FixModal({ originalCode, language, bugs, onClose }: FixModalProps) {
  const [loading, setLoading] = useState(false);
  const [fixResult, setFixResult] = useState<FixResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const runFix = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/ai-fix', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: originalCode, language, bugs }),
      });
      const data: FixResponse = await res.json();
      if (data.error) setError(data.error);
      else setFixResult(data);
    } catch {
      setError('Network error. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const copyFixed = () => {
    if (fixResult?.fixedCode) {
      navigator.clipboard.writeText(fixResult.fixedCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className={styles.modalOverlay} onClick={onClose}>
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <div className={styles.modalHeader}>
          <div className={styles.modalTitle}>
            <span>🤖</span>
            <span>AI Auto-Fix</span>
          </div>
          <button className={styles.modalClose} onClick={onClose}>✕</button>
        </div>

        <div className={styles.modalBody}>
          {!fixResult && !loading && !error && (
            <div className={styles.fixIntro}>
              <p>Claude AI will fix <strong>{bugs.length} issue{bugs.length !== 1 ? 's' : ''}</strong> in your {language} code.</p>
              <ul className={styles.fixList}>
                {bugs.slice(0, 5).map((b) => (
                  <li key={b.id} className={styles[b.severity]}>
                    [{b.severity.toUpperCase()}] L{b.line}: {b.title}
                  </li>
                ))}
                {bugs.length > 5 && <li className={styles.moreItems}>... and {bugs.length - 5} more</li>}
              </ul>
              <button className={styles.fixRunBtn} onClick={runFix}>
                ▶ Generate Fixed Code
              </button>
            </div>
          )}

          {loading && (
            <div className={styles.fixLoading}>
              <div className={styles.fixSpinner} />
              <p>Claude is rewriting your code...</p>
            </div>
          )}

          {error && (
            <div className={styles.fixError}>
              <p>⚠ {error}</p>
              <button className={styles.fixRunBtn} onClick={runFix} style={{ marginTop: '12px' }}>Try Again</button>
            </div>
          )}

          {fixResult && !error && (
            <div className={styles.fixResult}>
              <div className={styles.fixChanges}>
                <div className={styles.fixChangesTitle}>Changes applied ({fixResult.changes?.length ?? 0}):</div>
                {fixResult.changes?.map((c, i) => (
                  <div key={i} className={styles.fixChange}>✓ {c}</div>
                ))}
              </div>

              <div className={styles.diffPanels}>
                <div className={styles.diffPanel}>
                  <div className={styles.diffLabel}>
                    <span className={styles.diffBefore}>ORIGINAL</span>
                  </div>
                  <CodeEditor
                    value={originalCode}
                    onChange={() => {}}
                    language={language}
                    onLanguageChange={() => {}}
                    readOnly
                  />
                </div>

                <div className={styles.diffPanel}>
                  <div className={styles.diffLabel}>
                    <span className={styles.diffAfter}>AI FIXED</span>
                  </div>
                  <CodeEditor
                    value={fixResult.fixedCode ?? ''}
                    onChange={() => {}}
                    language={language}
                    onLanguageChange={() => {}}
                    readOnly
                  />
                </div>
              </div>

              <div className={styles.fixActions}>
                <button className={styles.copyFixBtn} onClick={copyFixed}>
                  {copied ? '✓ Copied!' : '⎘ Copy Fixed Code'}
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default function BugReport({ result, originalCode }: BugReportProps) {
  const [showFixModal, setShowFixModal] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [filterSeverity, setFilterSeverity] = useState<Severity | 'all'>('all');

  const filteredBugs = filterSeverity === 'all'
    ? result.bugs
    : result.bugs.filter((b) => b.severity === filterSeverity);

  const scoreColor =
    result.score >= 80 ? styles.success :
    result.score >= 50 ? styles.warning : styles.critical;

  return (
    <div className={styles.reportContainer}>
      {/* Summary Cards */}
      <div className={styles.summary}>
        <div className={`${styles.summaryCard} ${scoreColor}`}>
          <div className={styles.summaryNum}>{result.score}</div>
          <div className={styles.summaryLabel}>Code Score</div>
        </div>
        <div
          className={`${styles.summaryCard} ${styles.critical} ${filterSeverity === 'critical' ? styles.activeFilter : ''}`}
          onClick={() => setFilterSeverity(filterSeverity === 'critical' ? 'all' : 'critical')}
          style={{ cursor: 'pointer' }}
          title="Click to filter by critical"
        >
          <div className={styles.summaryNum}>{result.criticalCount}</div>
          <div className={styles.summaryLabel}>Critical</div>
        </div>
        <div
          className={`${styles.summaryCard} ${styles.warning} ${filterSeverity === 'warning' ? styles.activeFilter : ''}`}
          onClick={() => setFilterSeverity(filterSeverity === 'warning' ? 'all' : 'warning')}
          style={{ cursor: 'pointer' }}
          title="Click to filter by warning"
        >
          <div className={styles.summaryNum}>{result.warningCount}</div>
          <div className={styles.summaryLabel}>Warnings</div>
        </div>
        <div
          className={`${styles.summaryCard} ${styles.info} ${filterSeverity === 'info' ? styles.activeFilter : ''}`}
          onClick={() => setFilterSeverity(filterSeverity === 'info' ? 'all' : 'info')}
          style={{ cursor: 'pointer' }}
          title="Click to filter by info"
        >
          <div className={styles.summaryNum}>{result.infoCount}</div>
          <div className={styles.summaryLabel}>Info</div>
        </div>
      </div>

      {/* Mode Badge + Summary */}
      <div className={styles.reportMeta}>
        {result.analysisMode === 'ai' ? (
          <span className={styles.aiBadge}>🤖 AI Analysis</span>
        ) : (
          <span className={styles.staticBadge}>⚡ Static Scan</span>
        )}
        <span className={styles.summaryText}>{result.summary}</span>
      </div>

      {/* AI Insights Panel */}
      {result.aiInsights && (
        <div className={styles.insightsPanel}>
          <div className={styles.insightsHeader}>
            <span>🧠</span>
            <span>AI Deep Insights</span>
          </div>
          <p className={styles.insightsText}>{result.aiInsights.overallAssessment}</p>

          {result.aiInsights.topPriorities && result.aiInsights.topPriorities.length > 0 && (
            <div className={styles.priorities}>
              <div className={styles.prioritiesTitle}>Top Priorities:</div>
              {result.aiInsights.topPriorities.map((p, i) => (
                <div key={i} className={styles.priority}>
                  <span className={styles.priorityNum}>{i + 1}</span>
                  <span>{p}</span>
                </div>
              ))}
            </div>
          )}

          <div className={styles.insightGrid}>
            {result.aiInsights.securitySummary && (
              <div className={styles.insightRow}>
                <span className={styles.insightLabel}>🔒 Security</span>
                <span>{result.aiInsights.securitySummary}</span>
              </div>
            )}
            {result.aiInsights.performanceSummary && (
              <div className={styles.insightRow}>
                <span className={styles.insightLabel}>⚡ Performance</span>
                <span>{result.aiInsights.performanceSummary}</span>
              </div>
            )}
            {result.aiInsights.architecturalNotes && (
              <div className={styles.insightRow}>
                <span className={styles.insightLabel}>🏗 Architecture</span>
                <span>{result.aiInsights.architecturalNotes}</span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Action Bar */}
      <div className={styles.actionBar}>
        {originalCode && result.totalBugs > 0 && (
          <button className={styles.actionBtn} onClick={() => setShowFixModal(true)}>
            🤖 Auto-Fix with AI
          </button>
        )}

        <div className={styles.exportContainer}>
          <button
            className={styles.actionBtnSecondary}
            onClick={() => setShowExportMenu(!showExportMenu)}
          >
            ↓ Export
          </button>
          {showExportMenu && (
            <div className={styles.exportMenu} onMouseLeave={() => setShowExportMenu(false)}>
              <button onClick={() => { exportAsJSON(result); setShowExportMenu(false); }}>
                {} JSON
              </button>
              <button onClick={() => { exportAsMarkdown(result); setShowExportMenu(false); }}>
                📝 Markdown
              </button>
              <button onClick={() => {
                navigator.clipboard.writeText(JSON.stringify(result, null, 2));
                setShowExportMenu(false);
              }}>
                ⎘ Copy JSON
              </button>
            </div>
          )}
        </div>

        {filterSeverity !== 'all' && (
          <span className={styles.filterNote}>
            {filteredBugs.length} {filterSeverity} shown ·{' '}
            <button onClick={() => setFilterSeverity('all')}>clear</button>
          </span>
        )}
      </div>

      {/* Bug List */}
      {result.totalBugs === 0 ? (
        <div className={styles.emptyState}>
          <div className={styles.emptyIcon}>✅</div>
          <div className={styles.emptyText}>No issues detected. Clean code!</div>
        </div>
      ) : (
        <div className={styles.bugList}>
          {filteredBugs.length === 0 ? (
            <div className={styles.emptyState}>
              <div className={styles.emptyText}>No {filterSeverity} issues found.</div>
            </div>
          ) : (
            filteredBugs.map((bug) => <BugItem key={bug.id} bug={bug} />)
          )}
        </div>
      )}

      {/* Fix Modal */}
      {showFixModal && originalCode && (
        <FixModal
          originalCode={originalCode}
          language={result.language}
          bugs={result.bugs}
          onClose={() => setShowFixModal(false)}
        />
      )}
    </div>
  );
}
